version: '3'

networks:
  devops-network:
    driver: bridge

services:
  devops-auth:
    container_name: devops-auth
    image: devops-auth:3.0
    ports:
      - 8080:8080
    networks:
      - devops-network
    depends_on:
      - mysql
    environment:
      - CONTEXT_PATH=/devops-auth
      - DATABASE_URL=jdbc:mysql://127.0.0.1:33066/school_management
      - DATABASE_USERNAME=school_management
      - DATABASE_PASSWORD=7Y2Cw5mebRpVSH8s
      - JWT_PRIVATE_KEY=MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAPq7AuaN8IKjC3h94kDhVMBu/5wArSrBb0xjLcXpRCKtAZQ6cLkJsGzlHwn5UCPHrggJ/1+jQRK30/AEtSf+IvklNyHbAYShw0sGlyP48vwF1djqZJPxOaUYNtjOjB4TqsS9/vBAB1JGxPUp8M8uCNKYzFrC+H5kS+7yhs/+pjx1AgMBAAECgYByLjn67oapp0BxBbrEWxkybRoAXBqADwj1W3Eb4MfDls/SRe7RhUUPwiOpchz5vlRVmt/uGLVopchhVHN/G++maXi6AV1eYpDxfcXpNZbd4Wy7cdbyaEsNeiP8B6cNlmPSimItAjBqfB1sT3WeAlmIsoNpUJi7wMwGjf5QUQ/nfQJBAP2WSadtM7vO/qRgXufYBAmHzyHQFF8UwfvcZlkhttbzexyrGcLJ3kv663RknjNsqc3ggl0G/Y96SFRb+4H7eXcCQQD9HcPuhHmo6bRY4vde1drCTltRWOymmz5Zfagqm/Z/TzCZTR5BWxd04C6Itn4GEKkdKbEPoEUXjhK2lskisbRzAkEAuVTSJav4yETC9C1+jyDf6ns4FbU2fjr0fvcYUgIC19wA2PXvkN3qOkt7M4ip2lmLTGzNueF3BRpQrF7BVMEOhwJBAI7ZzKmBdJQDCbicp5WLRkIhLOJ1OGIy/XZON6mMigqBq+DpKCkketGIcFrR+7/6iScfT4GNJ1FK6n7IDM4a0scCQFxlcH3YNJjGKXh2b/HOt5bnpF4NI/pJ6po9dcHy+Wf76i+/0JB/dG3H5h7NQTIIKo6KEHlEcWnOYqVJRhnBVEo=
      - JWT_PUBLIC_KEY=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQD6uwLmjfCCowt4feJA4VTAbv+cAK0qwW9MYy3F6UQirQGUOnC5CbBs5R8J+VAjx64ICf9fo0ESt9PwBLUn/iL5JTch2wGEocNLBpcj+PL8BdXY6mST8TmlGDbYzoweE6rEvf7wQAdSRsT1KfDPLgjSmMxawvh+ZEvu8obP/qY8dQIDAQAB

  mysql:
    container_name: mysql-devops
    image: mysql:5.7
    restart: always
    ports:
      - 33066:3306
    networks:
      - devops-network
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
    #    entrypoint: sh -c "/init.sh"
    environment:
      - MYSQL_ROOT_PASSWORD=minhkudo
      - MYSQL_PASSWORD=7Y2Cw5mebRpVSH8s
      - MYSQL_USER=school_management
      - MYSQL_DATABASE=school_management


      #  redis:
      #    container_name: redis-devops
      #    image: 'bitnami/redis:6.2'
      #    ports:
      #      - "127.0.0.1:6379:6379"
      #    environment:
      #      - ALLOW_EMPTY_PASSWORD=yes
      #    networks:
      #      - app-tier
      #
      #  zookeeper:
      #    container_name: zookeeper-devops
      #    image: wurstmeister/zookeeper
      #    ports:
      #      - "2181:2181"
      #
      #  kafka:
      #    container_name: kafka-devops
      #    image: wurstmeister/kafka
      #    ports:
      #      - 9092:9092
      #    environment:
      #      KAFKA_ADVERTISED_HOST_NAME: localhost
      #      KAFKA_BROKER_ID: 1
      #      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      #      KAFKA_LISTENERS: "PLAINTEXT://:9092"
      #    depends_on:
      #      - zookeeper
      #    restart: on-failure
      #    volumes:
      #      - ./data/kafka/docker.sock:/var/run/docker.sock

      #  elasticsearch:
      #     image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
      #     container_name: elasticsearch
      #     volumes:
      #      - ./elasticsearch-data:/usr/share/elasticsearch/data
      #     ports:
      #      - "9200:9200"
      #      - "9300:9300"
      #     environment:
      #       - discovery.type=single-node
      #       - cluster.name=es-docker-cluster
      #       - node.master=true
      #       - node.data=true
      #       - bootstrap.memory_lock=true
      #       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

      #  kibana:
      #    container_name: kibana
      #    image: docker.elastic.co/kibana/kibana:7.4.0
      #    environment:
      #      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      #    ports:
      #      - 5601:5601
      #    depends_on:
      #      - elasticsearch

