version: '3'

networks:
  app-tier:
    driver: bridge

services:
  mysql:
    container_name: mysql-devops
    image: mysql:8
    restart: always
    ports:
      - 33066:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    environment:
      - MYSQL_ROOT_PASSWORD=minhkudo
      - MYSQL_PASSWORD=7Y2Cw5mebRpVSH8s
      - MYSQL_USER=school_management
      - MYSQL_DATABASE=school_management


  redis:
    container_name: redis-devops
    image: 'bitnami/redis:6.2'
    ports:
      - "127.0.0.1:6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier

  zookeeper:
    container_name: zookeeper-devops
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka-devops
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LISTENERS: "PLAINTEXT://:9092"
    depends_on:
      - zookeeper
    restart: on-failure
    volumes:
      - ./data/kafka/docker.sock:/var/run/docker.sock

      #  elasticsearch:
      #     image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
      #     container_name: elasticsearch
      #     volumes:
      #      - ./elasticsearch-data:/usr/share/elasticsearch/data
      #     ports:
      #      - "9200:9200"
      #      - "9300:9300"
      #     environment:
      #       - discovery.type=single-node
      #       - cluster.name=es-docker-cluster
      #       - node.master=true
      #       - node.data=true
      #       - bootstrap.memory_lock=true
      #       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

      #  kibana:
      #    container_name: kibana
      #    image: docker.elastic.co/kibana/kibana:7.4.0
      #    environment:
      #      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      #    ports:
      #      - 5601:5601
      #    depends_on:
      #      - elasticsearch

