kind: Deployment
apiVersion: apps/v1
metadata:
  name: devops-auth
spec:
  selector:
    matchLabels:
      app: devops-auth
  replicas: 1
  template:
    metadata:
      labels:
        app: devops-auth
        version: v1
    spec:
      containers:
        - name: devops-auth
          image: devops-auth:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: devops-service
spec:
  type: NodePort
  selector:
    app: devops
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000
