kind: Deployment
apiVersion: apps/v1
metadata:
  name: devops-liquibase
spec:
  selector:
    matchLabels:
      app: devops-liquibase
  replicas: 1
  template:
    metadata:
      labels:
        app: devops-liquibase
        version: v1
    spec:
      containers:
        - name: devops-liquibase
          image: devops-liquibase:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: devops-liquibase
            - secretRef:
                name: devops-liquibase
      restartPolicy: Always
volumes:

---
apiVersion: v1
kind: Service
metadata:
  name: devops-service
spec:
  type: NodePort
  selector:
    app: devops
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000